locale: en_US.UTF-8
timezone: Asia/Tokyo
ssh_key_file: ~/.ssh/id_rsa.pub
sysadmin: postmaster@example.com
open_ports: 22

database:
  name: postfix
  provider: mysql
  host: __REPLACE_DATABASE_HOST__
  port: __REPLACE_DATABASE_PORT__
  user: postfix
  password: __REPLACE_DATABASE_PASSWORD__

domain: 192.168.33.101.xip.io
mailname: mailserver.local
configure_hostname: true
inventory_hostname: 192.168.33.101.xip.io

vmail_user: vmail
vmail_uid: 150
vmail_group: mail
vmail_gid: 8
vmail_dir: /var/vmail

postfixadmin:
  dest: /opt
  dirname: postfixadmin-2.3.7
  tarball: http://downloads.sourceforge.net/project/postfixadmin/postfixadmin/postfixadmin-2.3.7/postfixadmin-2.3.7.tar.gz
  setup_password: __REPLACE_POSTFIXADMIN_SETUP_PASSWORD__