- name: Preconfigure postfix
  shell: bash -c 'debconf-set-selections <<< "postfix postfix/{{item.key}} string {{item.value}}"'
  with_items:
    - key: mailname
      value: "{{ mailname }}"

- name: Install essential packages
  apt: pkg={{ item }} state=installed force=yes
  with_items:
    - bcrypt
    - bsd-mailx
    - curl
    - dovecot-core
    - dovecot-imapd
    - dovecot-managesieved
    - dovecot-pop3d
    - dovecot-sieve
    - dovecot-mysql
    - git
    - libgpgme11
    - libpth20
    - logrotate
    - mutt
    - postfix
    - postfix-mysql
    - postgrey
    - procmail
    - pwgen
    - ssl-cert
    - php5
    - php5-mysql
    - php5-curl
    - php5-imap
